version: '3.7'

# DCKHUB=devoinc/ docker-compose -f docker-devo-relay.yml up -d
# Connect to container: docker exec -it Devo-Relay /bin/bash
### Check the relay:
# for i in $( seq 150 ) ; do echo "<14>$( date --iso-8601=seconds ) docker-relay test.keep.free: Docker Devo-Relay test event # $i" | nc -N localhost 13000 ; done
#####

networks:
  devoring:

services:
  Devo-Relay:
    image: ${DCKHUB}devo-relay:1.1.6
    hostname: Relay
    container_name: Devo-Relay
    restart: always
    environment:
      - DUMMYSTAT=0
      # UNCOMMENT THE NEXT ENVIROMENT VARIABLE TO USE RELAY IN Cloud/OnPREM with SELFSIGNED CERTS
      # - SELFSIGNED=1
      # Set the right DEVO WEB in LOGTRUST_WEB va: eu.devo.com | us.devo.com | es.devo.com
      - LOGTRUST_WEB=https://eu.devo.com
      # Set the right end point for the choosed Devo cloud
      - LOGTRUST_ENDPOINT=eu.elb.relay.logtrust.net
      # Set the right secure port to send data to Devo
      - LOGTRUST_PORT=443
      # Set the name for the relay, usually relay-domain_name
      - RELAY_NAME=docker-relay-domain
      # Set valid APIKEY for the domain
      - RELAY_APIKEY=YOUR_API_KEY
      # Set proxy values if it's necessary in for your network. Default empty values are not applied
      - PROXY_HOST=
      - PROXY_PORT=
      - PROXY_USER=
      - PROXY_PASS=
    ports:
     - 12999-13030:12999-13030
    volumes:
       ###App persisten information
       - ./conf/docker-start:/opt/devo/docker-start
       - type: bind
         source: "./conf/relay-data"
         target: "/opt/devo/relay-data"
       - type: bind
         source: "./conf/rules"
         target: "/etc/logtrust/scoja/current/rules"
       - type: bind
         source: "./conf/unrules"
         target: "/etc/logtrust/scoja/current/unrules"
       - type: bind
         source: "./conf/keys"
         target: "/etc/logtrust/scoja/current/keys"
       - type: bind
         source: "./conf/logs"
         target: "/var/log"
    networks:
       devoring:
         aliases:
           - DevoRelay
    # To debug comment the next line
    command: /opt/devo/docker-start
    logging:
      driver: none

### END
