#!/bin/bash

set -e

if [ $SELFSIGNED == "1" ]; then
  export PYTHONHTTPSVERIFY=0
  echo "export PYTHONHTTPSVERIFY=0" > /opt/devo/relay-data/selfsigned
else
  rm -f /opt/devo/relay-data/selfsigned
fi

envtpl --keep-template /etc/logtrust/relay/logtrust.conf.tpl
envtpl --keep-template /etc/logtrust/scoja/version1/local.py.tpl
echo "" > /opt/devo/relay-data/scoja.pid

chmod 600 /etc/logtrust/relay/logtrust.conf /etc/logtrust/scoja/version1/local.py

### Recovery connection if it exists previously
if [ -f "/opt/devo/relay-data/pass.temp" ]; then
  newpass=`cat /opt/devo/relay-data/pass.temp |cut -d"=" -f2|sed 's/\//'"\\\\\\\\\/"'/g'`
  sed -i -e 's/keypass = \".*\"/keypass = \"'"${newpass}"'\"/' /etc/logtrust/scoja/current/local.py
fi

/opt/logtrust/relay/UpdateRelay.py  > /var/log/lt-relay.log 2>&1

runPath=/opt/devo/run
LockFile=scoja
FILE="${runPath}/${LockFile}.lock"
if [ ! -f "$FILE" ]; then
  touch $FILE
  /opt/logtrust/scoja/scoja.sh -r 5s -G /etc/logtrust/scoja/version1/all-me.conf -j /etc/logtrust/scoja/version1/all-var.conf > /var/log/scoja.log 2>&1 &
  echo $! > /opt/devo/relay-data/scoja.pid
fi

/usr/sbin/cron -f

### END
